name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'
        project_id: ims-poc1
        service_account_key: ${{ secrets.GCP_SA_KEY }}
 

    - name: Authenticate with service account
      run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/ims-poc1/inventory-service:$GITHUB_SHA .
        docker push gcr.io/ims-poc1/inventory-service:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy inventory-service \
          --image gcr.io/ims-poc1/inventory-service:$GITHUB_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated